name: Deploy

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set Up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Dependencies
      run: |
        make install-dependencies

    - name: Docker
      run: make build        

    - name: Documentation
      run: make docs
    
    - name: Lint code
      run: pylint src
      continue-on-error: true

    - name: Run tests
      run: |
        pytest tests
        pytest --cov
      continue-on-error: true

    - name: Configure authentication
      run: poetry config http-basic.pypi jpaulohe4rt ${{ secrets.PWD }}
    - name: Publish package
      run: |
        poetry build
        poetry publish
